spring:
  application:
    name: monitor-backend

server:
  port: 8080

logging:
  level:
    divera.response: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method