spring:
  application:
    name: monitor-backend

server:
  port: 8080
  shutdown: graceful

  spring:
    lifecycle:
      timeout-per-shutdown-phase: 30s

logging:
  level:
    divera.response: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: monitor-backend